# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 702e41c992148996213d5809cb921bd8fe61773c15a8cb2bd25e3a6eedb47d827d6d9fc974f031e8688d8a8548794c13f1503790893113d5b8c810d6cd2eb824
  # The site_key below is not actually a secret, but it's included in this file
  # anyway for convenience.
  recaptcha_site_key: 6LciqycUAAAAAGPAgwudo2DpuPd1gUgMhR0c9v01
  recaptcha_secret: <%= ENV["RECAPTCHA_SECRET"] %>

test:
  secret_key_base: 83746e0610dbd4087d02144290ceff8667a847bc5f8f555100e18304851d768feab4e013496e526ab193dd934f2f3ea91ca29072617d57d0ca80c78464d72a4c
  recaptcha_secret: <%= ENV["RECAPTCHA_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # The site_key below is not actually a secret, but it's included in this file
  # anyway for convenience.
  recaptcha_site_key: 6LewsicUAAAAAJ5dowJeY2sPLrsy-EFyRsSm9wWq
  recaptcha_secret: <%= ENV["RECAPTCHA_SECRET"] %>
